# main.py

from modules.ope import OPE, process_object_names
from modules.ope_score import OPE_score
from modules.ope_score_par import OPE_score_par
from modules.ope_mat import OPE_mat
from modules.urp import URP
from modules.urp_risk import URP_risk
from modules.pl_posneg import make_options, POSNEG
from modules.pl_toplog import TOPLOG, make_options
from modules.pl_toplog_prop import TOPLOG_prop
from modules.pl_iter import ITER
#from modules.kg_yolo import KG_YOLO
#from modules.pick_and_place import PickAndPlace  
#from frankapy import FrankaArm
import numpy as np
#from autolab_core import RigidTransform
#import rospy

def main():

    
    # pick_place = PickAndPlace()

    # pick_place.return_to_rest()

    # Different Configurations
    use_yolo = False

    use_proc_names = False

    # OPE with Yes/No
    use_OPE = False
    # OPE with Materials
    use_OPE_mat = False
    # OPE with Scores
    use_OPE_score = False
    # OPE with Risk Index and Fallback Mechanism
    use_OPE_score_par = False

    # URP 
    use_URP = False
    use_OPEinURP = False
    # URP with Risk Index
    use_URP_risk = False
    use_OPERiskinURP = False

    # Planner
    use_posneg = False
    use_toplog = True
    use_toplog_prop = False
    use_iter = False
    

    # Planner: Positive and Negative Prompting
    use_rpn=False
    use_bbox=False
    use_properties=True

    # if use_yolo:
    #     # Call the YOLO to get objects and coordinates
    #     found_objects, object_centers = KG_YOLO()

    #     print("Detected Objects:", found_objects)
    #     print("Object Centers:")
    #     for obj in object_centers:
    #         obj_str=str(obj[0])
    #         print("\nNome: ", obj_str)
    #         print("Coordinate:", obj[1], obj[2], obj[3])
    
    # User Request
    user_query = "Give me something to eat"

    # Founded Objects
    config = {
    'pick': ['pasta', 'chips', 'meat', 'blue block',],
    'place': ['table', 'trash can', 'fridge', 'user']
    }

    found_objects = ['pasta', 'chips', 'meat', 'blue block', 'table', 'trash can', 'fridge', 'user']
    
    
    rel_objects = found_objects 

    num_pick = len(config['pick'])
    num_place = len(config['place'])
    num_box = num_pick + num_place

    PICK_TARGETS = {item: None for item in config['pick']}
    PLACE_TARGETS = {item: None for item in config['place']}

    options = make_options(PICK_TARGETS, PLACE_TARGETS)

    
    print("\nUser Request:") 
    print(user_query)


    if use_proc_names:
        found_objects_proc = process_object_names(found_objects)
    else:
        found_objects_proc = found_objects

    # Object Properties Extraction (OPE)
    if use_OPE:
        objects_info = OPE(found_objects_proc, rel_objects)
        print("\nFinal objects information:")
        print(objects_info)
    elif use_OPE_mat:
        objects_info = OPE_mat(found_objects_proc, rel_objects)
        print("\nFinal objects information:")
        print(objects_info)
    elif use_OPE_score:
        objects_info = OPE_score(found_objects_proc, rel_objects)
        print("\nFinal objects information:")
        print(objects_info)
    elif use_OPE_score_par:
        objects_info = OPE_score_par(found_objects_proc, rel_objects, user_query)
        print("\nFinal objects information:")
        print(objects_info)
    else:
        objects_info = {}
   
    # User Request Processing (URP)
    if use_URP:
        urp_query = URP(user_query, found_objects, objects_info, use_OPEinURP, rel_objects)
    elif use_URP_risk:
        urp_query = URP_risk(user_query, found_objects, objects_info, use_OPERiskinURP, rel_objects)
    else:
        urp_query = user_query
    


    print("\nQuery for the planner:") 
    print(urp_query)


    PICK_TARGETS = {item: None for item in config['pick']}
    PLACE_TARGETS = {item: None for item in config['place']}
    PLACE_TARGETS.update({item: None for item in config['pick']})
    print("PICK_TARGETS:", PICK_TARGETS)
    print("PLACE_TARGETS:", PLACE_TARGETS)

    # Planners 
    max_tasks = 20

    # Positive and Negative Prompting

    # Maximum gripper opening value
    max_gripper_size = 0.08 #cm

    # From Object Detection:
    rpn_scores = []
    rescaled_detection_boxes = []
    if use_posneg:
        policy_posneg = POSNEG(user_query, max_tasks, PICK_TARGETS, PLACE_TARGETS, urp_query, found_objects, rpn_scores, rescaled_detection_boxes, max_gripper_size, objects_info, use_rpn, use_bbox, use_properties)
        print('\nPolicy generated by Positive and negative prompting:')
        print(policy_posneg)

    if use_toplog:
        policy_toplog = TOPLOG(found_objects, PICK_TARGETS, PLACE_TARGETS, urp_query)
        print("\nPolicy generated by TopLogprob:", policy_toplog)

    if use_toplog_prop:
        policy_toplog_prop = TOPLOG_prop(found_objects, PICK_TARGETS, PLACE_TARGETS, urp_query, objects_info)
        print("\nPolicy generated by TopLogprob with properties:", policy_toplog_prop)

    if use_iter:
            policy_iter = ITER(found_objects, PICK_TARGETS, PLACE_TARGETS, user_query, model="gpt-4o-mini", limit_num_options=3, verbose=True, top_logprobs = 5)
            print("\nPolicy generated by Iteration Alg.:", policy_iter)

    quit()


    
    # fa = FrankaArm()

    # # Policy development to perform pick and place operations
    # for action in policy_posneg:
    #     if "robot.pick_and_place" in action:
    #         # Extract the parameters inside the parentheses
    #         try:
    #             params = action[action.find("(")+1 : action.find(")")]
    #             object_name, place_location = [param.strip() for param in params.split(",")]
    #             print(f"Processing action: Pick {object_name} and Place in {place_location}")

    #             # Find the coordinates of the object to be picked up
    #             object_coord = None
    #             for obj in object_centers:
    #                 if obj[0].lower() == object_name.lower():
    #                     object_coord = obj[1:4]
    #                     break

    #             if object_coord is not None:
    #                 # Perform the pick operation
    #                 pick_place.pick_object(object_name, object_coord)

    #                 # Perform gripper closure
    #                 pick_place.closing_gripper(object_name, object_coord, objects_info)

    #                 # Find the coordinates of the location of place
    #                 place_coord = None
    #                 for obj in object_centers:
    #                     if obj[0].lower() == place_location.lower():
    #                         place_coord = obj[1:4]
    #                         break

    #                 if place_coord is not None:
    #                     # Perform place operation
    #                     pick_place.place_object(place_location, place_coord)

    #                     # Perform gripper opening
    #                     pick_place.opening_gripper(place_location, place_coord)

    #                     fa.open_gripper()

    #                     pick_place.opening_gripper_2(place_location, place_coord)

    #                     # Return to resting position
    #                     pick_place.return_to_rest()
    #                 else:
    #                     print(f"Errore: Place location '{place_location}' not found in detections.")
    #             else:
    #                 print(f"Errore: Object '{object_name}' not found in detections.")
    #         except Exception as e:
    #             print(f"Error in the processing of the action '{action}': {e}")



if __name__ == "__main__":
    main()
